#!/usr/bin/sh

list_flags="-Si"
action_flags="-S"
placeholder="Install package ..."
success="Installed"
failure="Failed to install"
extra_args=""

open_url_kbd="Control+o"

while getopts ":rR" Option; do
  case $Option in
    r) # remove package
      list_flags="-Qi"
      action_flags="-Rns"
      placeholder="Remove package ..."
      success="Removed"
      failure="Failed to remove"
      ;;
    R) # search with regexp
      extra_args="-matching regex"
      placeholder="Install package (regex search) ..."
      ;;
    *) ;;
  esac
done

# shellcheck disable=2016
awk_str='
/^Name/{name=$2}
/^Description/{description=$2}
/^Download Size/{size=$2" →"}
/^Installed Size/{size_i=$2;
print name, "「 "size, size_i" 」", description}'

open_url() {
  pacman "$list_flags" "$1" | awk -F ' : ' '/^URL/{print $2}' | xargs xdg-open
}

notify() {
  # shellcheck disable=2015
  which say && say "$1" || notify-send "$1"
}

entry=$(
  # shellcheck disable=SC2086
  pacman "$list_flags" | awk -F ' : ' "$awk_str" | sort -d |
    rofi -dmenu $extra_args -i \
      -theme-str "#entry { placeholder: \"$placeholder\"; }" \
      -kb-custom-1 "$open_url_kbd"
)

rofi_exit=$?

[ $rofi_exit -eq 1 ] && exit

pkg=$(echo "$entry" | awk '{print $1}')

case $rofi_exit in
  10) open_url "$pkg" ;;
  *)
    if sudo pacman "$action_flags" --noconfirm "$pkg"; then
      notify "$success 📦 $pkg"
    else
      notify "$failure 📦 $pkg"
    fi
    ;;
esac

exit 0
